package com.fwhyn.app.gethub.feature.screen.profile.model

data class GitHubUserProfileUi(
    val login: String,
    val id: Int,
    val nodeId: String,
    val avatarUrl: String,
    val gravatarId: String,
    val url: String,
    val htmlUrl: String,
    val followersUrl: String,
    val followingUrl: String,
    val gistsUrl: String,
    val starredUrl: String,
    val subscriptionsUrl: String,
    val organizationsUrl: String,
    val reposUrl: String,
    val eventsUrl: String,
    val receivedEventsUrl: String,
    val type: String,
    val userViewType: String,
    val siteAdmin: Boolean,
    val name: String,
    val company: String?,
    val blog: String?,
    val location: String?,
    val email: String?,
    val hireable: Boolean?,
    val bio: String?,
    val twitterUsername: String?,
    val publicRepos: Int,
    val publicGists: Int,
    val followers: Int,
    val following: Int,
    val createdAt: String,
    val updatedAt: String,
) {
    companion object {
        fun default(
            login: String = "",
            id: Int = 0,
            nodeId: String = "",
            avatarUrl: String = "",
            gravatarId: String = "",
            url: String = "",
            htmlUrl: String = "",
            followersUrl: String = "",
            followingUrl: String = "",
            gistsUrl: String = "",
            starredUrl: String = "",
            subscriptionsUrl: String = "",
            organizationsUrl: String = "",
            reposUrl: String = "",
            eventsUrl: String = "",
            receivedEventsUrl: String = "",
            type: String = "",
            userViewType: String = "",
            siteAdmin: Boolean = false,
            name: String = "",
            company: String? = null,
            blog: String? = null,
            location: String? = null,
            email: String? = null,
            hireable: Boolean? = null,
            bio: String? = null,
            twitterUsername: String? = null,
            publicRepos: Int = 0,
            publicGists: Int = 0,
            followers: Int = 0,
            following: Int = 0,
            createdAt: String = "",
            updatedAt: String = "",
        ): GitHubUserProfileUi {
            return GitHubUserProfileUi(
                login = login,
                id = id,
                nodeId = nodeId,
                avatarUrl = avatarUrl,
                gravatarId = gravatarId,
                url = url,
                htmlUrl = htmlUrl,
                followersUrl = followersUrl,
                followingUrl = followingUrl,
                gistsUrl = gistsUrl,
                starredUrl = starredUrl,
                subscriptionsUrl = subscriptionsUrl,
                organizationsUrl = organizationsUrl,
                reposUrl = reposUrl,
                eventsUrl = eventsUrl,
                receivedEventsUrl = receivedEventsUrl,
                type = type,
                userViewType = userViewType,
                siteAdmin = siteAdmin,
                name = name,
                company = company,
                blog = blog,
                location = location,
                email = email,
                hireable = hireable,
                bio = bio,
                twitterUsername = twitterUsername,
                publicRepos = publicRepos,
                publicGists = publicGists,
                followers = followers,
                following = following,
                createdAt = createdAt,
                updatedAt = updatedAt
            )
        }
    }
}

val gitHubUserProfileUiFake = GitHubUserProfileUi(
    login = "fwhyn",
    id = 1,
    nodeId = "MDQ6VXNlcjE=",
    avatarUrl = "https://avatars.githubusercontent.com/u/1?v=4",
    gravatarId = "",
    url = "https://api.github.com/users/fwhyn",
    htmlUrl = "https://github.com/fwhyn",
    followersUrl = "https://api.github.com/users/fwhyn/followers",
    followingUrl = "https://api.github.com/users/fwhyn/following{/other_user}",
    gistsUrl = "https://api.github.com/users/fwhyn/gists{/gist_id}",
    starredUrl = "https://api.github.com/users/fwhyn/starred{/owner}{/repo}",
    subscriptionsUrl = "https://api.github.com/users/fwhyn/subscriptions",
    organizationsUrl = "https://api.github.com/users/fwhyn/orgs",
    reposUrl = "https://api.github.com/users/fwhyn/repos",
    eventsUrl = "https://api.github.com/users/fwhyn/events{/privacy}",
    receivedEventsUrl = "https://api.github.com/users/fwhyn/received_events",
    type = "User",
    userViewType = "Default",
    siteAdmin = false,
    name = "fwhyn",
    company = "GetHub",
    blog = "https://fwhyn.dev",
    location = "Earth",
    email = "fwhyn@example.com",
    hireable = true,
    bio = "Android developer",
    twitterUsername = "fwhyn",
    publicRepos = 42,
    publicGists = 7,
    followers = 100,
    following = 50,
    createdAt = "2011-01-25T18:44:36Z",
    updatedAt = "2024-06-30T12:00:00Z"
)